### ISSUE TITLE
Can't choose which wallet to connect to

### ISSUE THREAD

**Issue by peyton-v5** [RootSoft/walletconnect-dart-sdk#60]
`// Create a connector
            final connector = WalletConnect(
              bridge: 'https://bridge.walletconnect.org',
              clientMeta: PeerMeta(
                name: 'WalletConnect',
                description: 'WalletConnect Developer App',
                url: 'https://walletconnect.org',
                icons: [
                  'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
                ],
              ),
            );`
`final session = await connector.createSession(
                chainId: 3,
                onDisplayUri: (uri) async {
                  //url_launcher
                  await launch(uri);
                },
              );`

There are many wallet apps (Rainbow, MetaMask, Trust, imToken) on my phone. When "connector.createSession()" is executed and opened with url_launcher, Rainbow is always opened, and the next wallet app can only be invoked by uninstalling Rainbow.
But I just want to open MetaMask

**Comment by RootSoft** [comment]
@peyton-v5 Are you using iOS by any chance? That's a [known behavior](https://docs.walletconnect.com/mobile-linking#for-ios).

You'll have to write your own modal for ios which parses the WalletConnect Registry in order to select a wallet to be launched, or use this package:
https://pub.dev/packages/walletconnect_qrcode_modal_dart
